language: node_js
node_js:
  - "0.10"

before_install:
 - travis_retry npm install -g gulp
 - travis_retry npm install -g coveralls@2.8.0 &> install-coveralls.log

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
 - gulp

after_success:
 - cat dist/coverage/*/lcov.info | coveralls && echo "Successfully sent coverage to https://coveralls.io"